### PR TITLE
Added Travis setup and coverage support.

### PR DESCRIPTION
**Pull request by matejak**

### CODE REVIEW

**Comment by matejak** [comment]
@evgenyz Tests pass on my machine, do you think that it could be a libyaml  0.1 vs 0.2 issue?

Edit: Possibly yes, as it also fails on RHEL7,8 and we ship `libyaml<0.2` on RHELs.

**Comment by matejak** [comment]
Nope, I have rebased and it still fails.

**Comment by evgenyz** [comment]
Explanation: https://github.com/crystal-lang/crystal/pull/6287. I'll make a proper fix

**Comment by evgenyz** [comment]
Fixed: https://github.com/OpenSCAP/yaml-filter/commit/a103af71ff827671ecfa3c9b7d7959b433a28ffa

**Comment by evgenyz** [comment]
LGTM. Thank you for assistance!

**Pull request merged**
